name:                omni-selenium
version:             0.1.0.0
github:              "angelpopov/omni-selenium"
license:             BSD3
author:              "Angel Popov"
maintainer:          "angelpopov@yahoo.com"
copyright:           "na"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            hello

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/angelpopov/omni-selenium#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - base
    - webdriver
    - text
    - async
    - time
executables:
  omni-selenium-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omni-selenium

tests:
  omni-selenium-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omni-selenium
